version: "3.8"
services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "8000:8000"
        volumes:
            - .:/var/www/html
        environment:
            - APP_ENV=local
            - APP_DEBUG=true
            - APP_KEY=base64:0yjF+iPQ0kENqTXF2trXtaBnjtjsyg/vtHQ7WBt703s=
            - DB_HOST=127.0.0.1
            - DB_PORT=3306
            - DB_DATABASE=newsroom
            - DB_USERNAME=root
            - DB_PASSWORD=usman@123
